[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
plugins = { path = "../plugins" }
utilities = { path = "../utilities" }

tokio = { version = "*", features = ["full"] }
lazy_static = { version = "*" }
